### PR TITLE
🍱 Update screenshots

### LINKED ISSUE #88: 🍱 Update Screenshots of bpmn-studio
#### Describe your issue

Currently there are a lot of screenshots of bpmn-studio that are outdated.

#### How can others reproduce the issue?

See this for example https://github.com/process-engine/documentation/blob/d9e8f556c56211c7a3ab272a9231e0c873b7ee84/bpmn-studio/task-list.png

#### Possible solution

Update the screenshots

- by hand :(
- find something to automate this :)

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by robpal94**
## What did you change?
This PR updates the screenshots on the _bpmn-studio_ page.

Fixes #88 

## How can others test the changes?
Look at the documentation in _bpmn-studio_

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [x] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

**Comment by robpal94** [comment]
> In my opinion, it would look better if the task-list is not empty.
@SteffenKn I don't know how I can add entries to the task list tbh 😕

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/161

**Comment by Paulomart** [comment]
We should also update the videos https://www.process-engine.io/documentation/getting-started/examples/hello-bpmn-world.html.

**Comment by robpal94** [comment]
@Paulomart https://github.com/process-engine/documentation/pull/101

**Comment by cmg-dev** [comment]
@alexanderkasten bitte mergen und deployen.

**Pull request merged**
